/**
 * The Word Ladder library: every ladder climbs from a word of the working
 * week (WORK, DESK, BOSS, TASK, FILE, MAIL…) to a word of the retired one
 * (GOLF, BOAT, NAPS, SONG, EASY…), one letter at a time.
 *
 * Written by hand, not searched for at print time: a ladder a machine finds
 * through a big dictionary passes through words like "TOFT" and "DOLT", and
 * a rung with no clue has many right answers. Every word here is an
 * everyday one, every rung has its own clue (one clue per word, shared by
 * every ladder that passes through it), and the tests prove each step
 * changes exactly one letter in place.
 *
 * Levels are the number of rungs to fill: Gentle 2–3 (with the changing
 * square shaded), Classic 3–4, Challenging 5–6.
 */

export type WlLevel = 'gentle' | 'classic' | 'challenging'

/** The first and last word are given; everything between is a rung. */
const GENTLE = [
  'WORK FORK FORM FARM',
  'WORK WORD WARD YARD',
  'WORK WORE WOKE JOKE',
  'WORK WORE WARE WAVE',
  'WORK WORE CORE COME HOME',
  'WORK CORK COOK COOL POOL',
  'WORK WORD WOOD FOOD',
  'WORK WORE WIRE HIRE HIKE',
  'WORK WORE SORE SURE SURF',
  'WORK PORK PORT POET POEM',
  'DESK DUSK DUST RUST REST',
  'DESK DECK PECK PACK PARK',
  'BOSS MOSS MOST MOAT BOAT',
  'BOSS BASS BATS CATS',
  'TASK TALK TALL TAIL SAIL',
  'TASK CASK CASE CAKE',
  'TASK TANK SANK SAND',
  'FILE FINE FIND BIND BIRD',
  'FILE FIVE LIVE LOVE',
  'MAIL MALL CALL CALM',
  'MAIL SAIL SOIL SOUL SOUP',
  'NOTE NONE LONE LONG SONG',
  'LIST FIST FISH WISH',
  'LIST LAST EAST EASY',
  'FAST PAST PART PARK',
  'RUSH RUSE RISE RIDE TIDE',
  'TEAM SEAM SWAM SWIM',
  'TEAM TRAM TRIM TRIP',
  'BELL BELT BOLT BOAT',
  'COST POST PEST NEST',
  'LATE LAKE LIKE HIKE',
  'TIRE WIRE WISE WISH',
]

const CLASSIC = [
  'WORK WORD WOOD GOOD GOLD GOLF',
  'WORK WORE WIRE WISE WISH FISH',
  'WORK CORK COOK BOOK BOOT BOAT',
  'WORK PORK PORT POST PEST REST',
  'WORK FORK FORT SORT SOFT SOFA',
  'WORK WORE WOKE WAKE LAKE',
  'WORK WORE WARE CARE CAKE',
  'WORK PORK PORE POSE ROSE',
  'WORK WORE MORE MOVE LOVE',
  'DESK DUSK DUST RUST RUSE ROSE',
  'BOSS MOSS MOST MUST RUST REST',
  'BOSS LOSS LOSE HOSE HOME',
  'BOSS BASS BASE EASE EASY',
  'BOSS MOSS MOPS MAPS NAPS',
  'TASK TANK SANK SANG SING',
  'TASK CASK CASE CAVE WAVE',
  'TASK TALK TALE TAME GAME',
  'TASK CASK CASH WASH WISH',
  'FILE FINE WINE WING SING',
  'FILE PILE PALE PALM CALM',
  'FILE TILE TALE TALK WALK',
  'FILE FINE FIND FOND FOOD',
  'MAIL SAIL SOIL SOUL SOUR TOUR',
  'NOTE ROTE RATE GATE GAME',
  'LIST LIFT LOFT SOFT SOFA',
  'LIST LOST COST COAT BOAT',
  'LIST LOST POST POET POEM',
  'FAST PAST PART CART CARD',
  'FAST FIST LIST LIFT GIFT',
  'LATE LUTE LURE SURE SURF',
  'TEAM TRAM TRAY PRAY PLAY',
  'SELL SEAL SEAM SWAM SWIM',
  'HARD HARE CARE CASE EASE EASY',
  'FORM FORT FOOT FOOL POOL',
  'PENS PANS PASS MASS MAPS NAPS',
  'RUSH RUSE ROSE HOSE HOME',
]

const CHALLENGING = [
  'FAST PAST PEST PEAT SEAT SLAT SLOT SLOW',
  'WORK PORK PORT POST PAST EAST EASY',
  'WORK WORE BORE BONE LONE LONG SONG',
  'WORK WORE WIRE WIFE LIFE LIFT GIFT',
  'WORK WORN CORN COIN COIL SOIL SOUL SOUP',
  'WORK CORK COOK COOL COIL SOIL SAIL',
  'WORK WORD FORD FOND FIND BIND BIRD',
  'WORK PORK PARK PARE PALE PALM CALM',
  'DESK DUSK DUST MUST MIST FIST FISH',
  'DESK DECK DOCK LOCK LACK LACE LAKE',
  'DESK DUSK DUNK SUNK SINK SING SONG',
  'DESK DUSK DUST MUST MIST LIST LIFT GIFT',
  'DESK DECK DOCK LOCK LOOK COOK COOL POOL',
  'BOSS LOSS LOSE LONE LONG SONG SING',
  'BOSS BASS BASE BAKE WAKE WOKE JOKE',
  'BOSS MOSS MASS MASK TASK TALK WALK',
  'TASK TALK TALL TOLL TOLD GOLD GOLF',
  'TASK TALK TALL TAIL SAIL SOIL SOUL SOUP',
  'TASK TANK BANK BARK BARN YARN YAWN DAWN',
  'TASK MASK MAST MOST POST POET POEM',
  'FILE FILL FELL FEEL FEED FLED FLEE FREE',
  'FILE FILL FELL SELL SEAL SEAM SWAM SWIM',
  'MAIL HAIL HALL HULL GULL GULF GOLF',
  'MAIL HAIL HAIR HEIR HEAR HEAD READ',
  'MAIL MALL WALL WELL WELD WEED SEED',
  'MAIL MALL MALE MAKE BAKE BIKE HIKE',
]

/**
 * One clue per rung word. Short enough to sit beside its rung in two lines
 * at large print, never containing the word it clues, and written so the
 * neighbouring rungs settle any doubt (BARK is a dog's woof here, and the
 * ladder around it leaves one word that fits).
 */
export const WL_CLUES: Readonly<Record<string, string>> = {
  BAKE: 'Make bread in the oven',
  BANK: 'Where your savings are kept',
  BARK: 'A dog’s woof, or a tree’s skin',
  BARN: 'Red farm building full of hay',
  BASE: 'Bottom part of a lamp',
  BASS: 'The deepest singing voice',
  BATS: 'Wooden sticks for baseball',
  BELT: 'It holds your trousers up',
  BIKE: 'Two wheels and two pedals',
  BIND: 'Tie tightly together',
  BOLT: 'A flash of lightning',
  BONE: 'A dog’s favorite thing to chew',
  BOOK: 'Something to read in bed',
  BOOT: 'Tall shoe for rain or snow',
  BORE: 'Make a hole with a drill',
  CALL: 'Ring someone on the phone',
  CARE: 'Look after with love',
  CART: 'Wheeled buggy on a golf course',
  CASE: 'A mystery for a detective',
  CASH: 'Paper money and coins',
  CASK: 'Wooden barrel in a cellar',
  CAVE: 'Dark hollow in a hillside',
  COAT: 'Wear it outdoors in winter',
  COIL: 'A loop of rope or garden hose',
  COIN: 'A penny, a nickel or a quarter',
  COME: 'The opposite of go',
  COOK: 'Make dinner on the stove',
  COOL: 'A little bit cold',
  CORE: 'The middle of an apple',
  CORK: 'Stopper in a bottle',
  CORN: 'Yellow vegetable on the cob',
  COST: 'The price of something',
  DECK: 'Wooden patio out back',
  DOCK: 'Where boats tie up',
  DUNK: 'Dip a cookie in your milk',
  DUSK: 'Evening, as the sun goes down',
  DUST: 'Gray powder on an old shelf',
  EASE: 'Comfort; freedom from worry',
  EAST: 'Where the sun comes up',
  FEED: 'Give bread to the ducks',
  FEEL: 'Touch with your fingers',
  FELL: 'Tumbled down',
  FILL: 'Pour right up to the brim',
  FIND: 'Discover what was lost',
  FINE: 'Okay; or very thin, like sand',
  FISH: 'Catch one with a rod and line',
  FIST: 'A tightly closed hand',
  FIVE: 'Toes on one foot',
  FLED: 'Ran away',
  FLEE: 'Run away fast',
  FOND: 'Liking something very much',
  FOOL: 'Silly person; April ___',
  FOOT: 'Twelve inches',
  FORD: 'Cross a shallow river',
  FORK: 'It sits beside the knife',
  FORM: 'Paper to fill in at the office',
  FORT: 'Stronghold with high walls',
  GATE: 'Way through a garden fence',
  GOLD: 'Precious yellow metal',
  GOOD: 'The opposite of bad',
  GULF: 'A large bay of the sea',
  GULL: 'Noisy seabird at the beach',
  HAIL: 'Little balls of falling ice',
  HAIR: 'What a barber cuts',
  HALL: 'A long corridor',
  HARE: 'A rabbit’s speedy cousin',
  HEAD: 'The top of your body',
  HEAR: 'Listen with your ears',
  HEIR: 'One who inherits',
  HIRE: 'Take on a new worker',
  HOSE: 'Garden tube for watering',
  HULL: 'The body of a ship',
  LACE: 'Delicate fabric full of holes',
  LACK: 'Be without; have too little',
  LAKE: 'Fresh water to fish or row on',
  LAST: 'At the very end',
  LIFE: 'Being alive; “the good ___”',
  LIFT: 'Raise up high',
  LIKE: 'Enjoy; be fond of',
  LIST: 'Things to buy, written down',
  LIVE: 'Make your home somewhere',
  LOCK: 'It opens with a key',
  LOFT: 'Room right under the roof',
  LONE: 'Only one; on its own',
  LONG: 'The opposite of short',
  LOOK: 'Use your eyes',
  LOSE: 'Misplace, like your glasses',
  LOSS: 'Not a win',
  LOST: 'Unable to find the way',
  LURE: 'Shiny bait on a fishing line',
  LUTE: 'Old stringed instrument',
  MAKE: 'Build or create',
  MALE: 'Man or boy',
  MALL: 'Big indoor shopping center',
  MAPS: 'Road guides for a long trip',
  MASK: 'Face cover at a costume party',
  MASS: 'A large heap',
  MAST: 'Tall pole that holds a sail',
  MIST: 'A light fog',
  MOAT: 'Water all round a castle',
  MOPS: 'Long-handled floor cleaners',
  MORE: 'Extra; “Please, some ___”',
  MOSS: 'Soft green growth on rocks',
  MOST: 'Nearly all',
  MOVE: 'Change homes',
  MUST: 'Have to',
  NONE: 'Not a single one',
  PACK: 'Fill a suitcase',
  PALE: 'Light in color',
  PALM: 'Tropical tree on a sandy beach',
  PANS: 'Pots and ___',
  PARE: 'Peel an apple with a knife',
  PARK: 'Leave the car in a space',
  PART: 'A role in a play',
  PASS: 'Go by; hand it over',
  PAST: 'Days gone by',
  PEAT: 'Dark soil for the garden',
  PECK: 'A bird’s tap with its beak',
  PEST: 'Garden bug on the lettuce',
  PILE: 'A tall stack',
  POET: 'Writer of verses',
  PORE: 'Study closely: ___ over',
  PORK: 'Chops or bacon, from the farm',
  PORT: 'Harbor for a cruise ship',
  POSE: 'Hold still for a photo',
  POST: 'Letters and parcels',
  PRAY: 'Hope with all your heart',
  RATE: 'Speed: “at a steady ___”',
  RIDE: 'Go on a horse or a bike',
  RISE: 'Get up; what the sun does',
  ROSE: 'Red flower with thorns',
  ROTE: 'Learned by ___ (by heart)',
  RUSE: 'A clever trick',
  RUST: 'Red-brown flakes on old iron',
  SAIL: 'Canvas that catches the wind',
  SANG: 'Did a tune in the choir',
  SANK: 'Went under the water',
  SEAL: 'Barking animal at the zoo',
  SEAM: 'Line where two pieces are sewn',
  SEAT: 'Somewhere to sit',
  SELL: 'The opposite of buy',
  SING: 'Perform a tune in the choir',
  SINK: 'Kitchen basin for the dishes',
  SLAT: 'One strip of a wooden blind',
  SLOT: 'Narrow opening for a coin',
  SOFT: 'Not hard; gentle to the touch',
  SOIL: 'Garden dirt',
  SONG: 'A tune with words',
  SORE: 'Aching, after a long walk',
  SORT: 'Arrange in order',
  SOUL: 'Spirit: “heart and ___”',
  SOUR: 'The taste of a lemon',
  SUNK: 'Gone to the bottom',
  SURE: 'Certain',
  SWAM: 'Did laps in the pool',
  TAIL: 'A happy dog wags it',
  TALE: 'A story',
  TALK: 'Chat',
  TALL: 'High, like a giraffe',
  TAME: 'Gentle, not wild',
  TANK: 'Glass home for goldfish',
  TASK: 'A job to do',
  TILE: 'Ceramic square on the floor',
  TOLD: 'Said; passed on the news',
  TOLL: 'Fee to cross a bridge',
  TRAM: 'Streetcar on rails',
  TRAY: 'Carry breakfast in bed on it',
  TRIM: 'Cut just a little',
  WAKE: 'Stop sleeping',
  WALL: 'Hang pictures on it',
  WARD: 'Section of a hospital',
  WARE: 'Pottery goods: kitchen___',
  WASH: 'Clean with soap and water',
  WEED: 'Unwanted garden plant',
  WELD: 'Join metal with great heat',
  WELL: 'Healthy; or a water source',
  WIFE: 'Married woman',
  WINE: 'Made from grapes in a vineyard',
  WING: 'A bird flies with it',
  WIRE: 'Thin metal thread',
  WISE: 'Knowing, like an old owl',
  WISH: 'Make one on a shooting star',
  WOKE: 'Stopped sleeping',
  WOOD: 'Logs for the fireplace',
  WORD: 'A dictionary entry',
  WORE: 'Had on, like a sweater',
  WORN: 'Old and threadbare',
  YARN: 'Wool for knitting',
  YAWN: 'A sleepy stretch of the mouth',
}

export interface WlLadder {
  /** `classic:work-golf-1`: level, start, finish, and which of that pair's ladders. */
  id: string
  /** Start, rungs, finish — in reading order, top to bottom. */
  words: readonly string[]
}

function ladders(level: WlLevel, lines: readonly string[]): WlLadder[] {
  const seen = new Map<string, number>()
  return lines.map((line) => {
    const words = line.split(' ')
    const pair = `${words[0]}-${words[words.length - 1]}`.toLowerCase()
    const n = (seen.get(pair) ?? 0) + 1
    seen.set(pair, n)
    return { id: `${level}:${pair}-${n}`, words }
  })
}

export const WL_LADDERS_BY_LEVEL: Readonly<Record<WlLevel, readonly WlLadder[]>> = {
  gentle: ladders('gentle', GENTLE),
  classic: ladders('classic', CLASSIC),
  challenging: ladders('challenging', CHALLENGING),
}
